load("@rules_cc//cc:cc_test.bzl", "cc_test")
cc_test(
    name = "two_threads_counter",
    size = "small",
    srcs = ["two_threads_counter.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "peterson",
    size = "small",
    srcs = ["peterson.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "a_lock",
    size = "small",
    srcs = ["Alock.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "backoff_lock",
    size = "small",
    srcs = ["backoff_lock.cc"],
     deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "bounded_queue",
    size = "small",
    srcs = ["bounded_queue.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "coarse_linked_list",
    size = "small",
    srcs = ["coarse_linked_list.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "coarse_stack",
    size = "small",
    srcs = ["coarse_stack.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "FIFO_RW_Lock",
    size = "small",
    srcs = ["FIFO_RW_Lock.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "Lazy_linked_list",
    size = "small",
    srcs = ["Lazy_linked_list.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "Simple_RW_Lock",
    size = "small",
    srcs = ["Simple_RW_Lock.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
cc_test(
    name = "bakery",
    size = "small",
    srcs = ["bakery.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)

cc_test(
    name = "high_mem_usage",
    size = "small",
    srcs = ["high_mem_usage.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//tl2:tl2"
    ],
)
