load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "tl2",
    hdrs = ["tl2.h", 
            "hash_table.h",
            "stm.h",
            "t_var.h",
            "types.h",
            "version_lock.h",
            "log.h",
            "state.h",
            "memory.h",
            "ankerl/unordered_dense.h",
            "ankerl/stl.h",
            "ska_sort.h",
            "op.h",
            "lock_guard.h"
            ],
    includes = ["."],
    visibility = ["//visibility:public"],
)
