load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ordered_linked_list",
    hdrs = ["ordered_ll.h"],
    deps = ["//tl2:tl2"],
    visibility = ["//visibility:public"],
)
cc_library(
    name = "linked_list",
    hdrs = ["linked_list.h"],
    deps = ["//tl2:tl2"],
    visibility = ["//visibility:public"],
)
cc_library(
    name = "hash_map",
    hdrs = ["hash_map.h"],
    deps = ["//tl2:tl2"],
    visibility = ["//visibility:public"],
)